### ISSUE TITLE
No clickable input with name btnG

### ISSUE THREAD

**Issue by borregs** [trizen/clyrics#15]
hey @trizen ! First things first: thanks alot for ur contributions and followups. Ive been a clyrics user for years now; however, on my ArchLinux_i686 machine I started getting this **new** error message after upgrading from the archlinuxi686(defunct) repos to the archlinux32 repos:

`No clickable input with name btnG at $HOME/perl5/lib/perl5/WWW/Mechanize.pm line 913.`

I have the following required deps installed:

- **extra/perl-lwp-protocol-https 6.07-3.0**
- **community/perl-www-mechanize 1.90-1.0**
 
If i turn on the debbugging options I get this before errmsg:

`** Title: <Red Hot Chili Peppers - Dani California Greatest Hits Album Out in L.A 1994>
 ** GET https://www.google.com/ ==> 200 OK (2s)
`
Any help would be greatly appreciated, if I figure it out on my end ill let u know.

**Comment by trizen** [comment]
Hi. I cannot confirm this issue. Make sure you're using the latest version of `clyrics`. The `btnG` button is no longer used since version 0.10 (https://github.com/trizen/clyrics/commit/fb36d9701179c790e53c83757c4cbe2bdbdd0d9c).

**Comment by borregs** [comment]
Thanks alot. That was it. However the AUR pkgbuild is quite outdated, and there are 2 to choose from, I was actually git pulling from the old one. Thanks Again!
