### ISSUE TITLE
There is no form named "f"

### ISSUE THREAD

**Issue by Ambrevar** [trizen/clyrics#2]
With latest git commit, it crashes on every query with

    There is no form named "f" at /usr/share/perl5/vendor_perl/WWW/Mechanize.pm line 1938.

Mechanize.pm is version 1.73.

**Comment by trizen** [comment]
I works here (with Mechanize version 1.74). Make sure that `LWP::Protocol::https` is installed as well.

If it's possible, please run `clyrics -d some song` and write here the results. Thanks

**Comment by Ambrevar** [comment]
Installing `LWP::Protocol::https` did the trick, even with 1.73. I'll update the dependencies in the Arch Linux packages.
