### ISSUE TITLE
Decode HTML entities for all plugins

### ISSUE THREAD

**Issue by natezb** [trizen/clyrics#4]
Nice work on clyrics, I really like it!

Currently only 4 of the plugins call `decode_entities` on the text they return, so I've noticed encoded HTML entities in some fetched lyrics.

Tell me if I'm wrong, but I think it would probably make the most sense to do the decoding in `get_lyrics()` instead, so that it gets applied to all the plugins automatically.

**Comment by trizen** [comment]
Your suggestion is actually very good and I applied it in the above commit. Thank you! :+1:
