### ISSUE TITLE
There is no form named "f"

### ISSUE THREAD

**Issue by mdibaiee** [trizen/clyrics#5]
Hey,
I've recently been getting this error:

```
There is no form named "f" at /usr/share/perl5/vendor_perl/WWW/Mechanize.pm line 1011.
```

Fact is, I cloned the code, and replaced `form_name => 'f'` by `form_id = 'tsf'` and it works. Not sure why though, google.com does indeed have a form named `f` (`$('[name="f"]')` returns the correct form).

Any idea about this?

P.S. I checked the older issue which was related to `perl-lwp-protocol-https`, I have that installed.

**Comment by trizen** [comment]
Thanks for reporting this issue. It was fixed in the above commit.

**Comment by borregs** [comment]
hey @trizen ! First things first: thanks alot for ur contributions and followups. Ive been a clyrics user for years now; however, on my ArchLinux_i686 machine I started getting this **new** error message after upgrading from the archlinuxi686(defunct) repos to the archlinux32 repos:

`No clickable input with name btnG at $HOME/perl5/lib/perl5/WWW/Mechanize.pm line 913.`

I have the following required deps installed:

- **extra/perl-lwp-protocol-https 6.07-3.0**
- **community/perl-www-mechanize 1.90-1.0**
 
If i turn on the debbugging options I get this before errmsg:

`** Title: <Red Hot Chili Peppers - Dani California Greatest Hits Album Out in L.A 1994>
 ** GET https://www.google.com/ ==> 200 OK (2s)
`
Any help would be greatly appreciated, if I figure it out on my end ill let u know.
